title: Project-Course2-KTH-Digital-Training-Equipment
description: hello world
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
